### ISSUE TITLE
Not so much of an issue but more of a request.

### ISSUE THREAD

**Issue by St4tikk** [d07RiV/diabloweb#109]
Would it be possible to get some basic directions for selfhosting this?  What needs to be installed server side, what the directory structure needs to look like, what pieces need to be put in from devilution and where they go, what needs to be copied in from the diablo iso (and where) other than the mpq.  I tried searching around but couldn't really find a set of directions to follow.  Thanks for this web port.  I've had a lot of fun with it!

**Comment by AJenbo** [comment]
This is the relevant fork of Devilution https://github.com/d07RiV/devilution

You don't need anything else from the ISO

I don't know if the multiplayer server part has been made public or not, but other then that this should be all you need, and afaik just dropping it in a folder should be enough, no run time server is needed for single player. The code hasn't been maintained for a few months so there are several known issues that have been fixed upstream so I would recommend using a maintained native port like https://github.com/diasurgical/devilutionX (also exists for Android and iOS) at this point.

**Comment by St4tikk** [comment]
What does the directory structure of a working install look like?  I've dumped the contents of the devilution zip in and tried moving some things around and I still can't seem to get it going.

**Comment by AJenbo** [comment]
@St4tikk what platform are you trying to get it running on?
